server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10

nacos:
  config:
    server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
